---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    networks: 
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
#      - PASSWORD=password #optional
#      - HASHED_PASSWORD= #optional
#      - SUDO_PASSWORD=password #optional
#      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /www/.code-server/config:/config
      - /www:/www
    ports:
      - 8443:8443
    restart: always

networks:
  web:
    name: web
    external: true
