services:
  qbit:
    image: linuxserver/qbittorrent:latest
    container_name: qbit
    restart: unless-stopped
    networks:
      - web    
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - TZ=Europe/Vilnius
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - ./docker/config:/config
      - /tmp/torrents:/downloads-incomplete
      - /mnt/sda1/samba/torrents:/downloads-complete
    ports:
      - '6881:6881'
      - '6881:6881/udp'

networks:
  web:
    name: web
    external: true