version: "3"

services:

  grafana:
    image: grafana/grafana:latest
    user: ${USER_ID}
    volumes:
      - ./config/grafana:/var/lin/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki
    
  loki:
    image: grafana/loki:2.9.8
    volumes:
      - ./config/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
      
  promtail:
    image: grafana/promtail:2.9.8
    volumes:
      - /var/log:/var/log  #map the log folder.
      - ./config/promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - loki
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  node-exporter:
    image: prom/node-exporter:latest
    network_mode: host # Not compatible with ports declaration. This service will expose port 9100.
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped

networks:
  loki:
