scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100'] # On AWS EC2, use the private IP address of the instance.
      - labels:
          name: value-for-the-name