version: '3'

services:

  maildev:
    image: maildev/maildev
    restart: unless-stopped
    networks: 
      - web
    container_name: maildev
    environment:
      - TZ=Europe/Vilnius
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  web:
    name: web
    external: true        