services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: dockerpass
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=32505856 --innodb-buffer-pool-size=256M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mariadb_data:
    driver: local
  mariadb_config:
    driver: local


networks:
  web:
    name: web
    external: true
