version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: always
    
    # Пользователь с UID:GID 1000:1000
    user: 1000:1000
    
    ports:
      - "8096:8096"  # HTTP веб-интерфейс
      - "8920:8920"  # HTTPS (опционально)
      - "7359:7359/udp"  # Auto-discovery (опционально)
      - "1900:1900/udp"  # DLNA (опционально)
    
    volumes:
      # Конфигурация Jellyfin
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      
      # Медиа файлы (только для чтения)
      - /mnt/sda1/samba/Music:/media/music:ro
      - /mnt/sda1/samba/Video:/media/video:ro
    
    environment:
      - JELLYFIN_PublishedServerUrl=https://media.self.xtweb.eu
      - TZ=Europe/Moscow  # Укажите вашу временную зону
      - VAAPI_DEVICE=/dev/dri/renderD128  # AMD VAAPI устройство
    
    # Для аппаратного ускорения AMD Radeon 780M
    devices:
      - /dev/dri:/dev/dri  # AMD VAAPI
    
    # Дополнительные опции для производительности
    tmpfs:
      - /tmp
    
networks:
  web:
    name: web
    external: true
