services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - web
    ports:
      - "6379:6379"
    volumes:
      - redis_container:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    tty: true
    
volumes:
  redis_container:
    driver: local

networks:
  web:
    name: web
    external: true
